dry_run: false
server:
  host: 127.0.0.1
  port: 9999
cloudflare:
  base_url: https://api.cloudflare.com/client/v4/
  account_id: "6b7610a08ea0b01e6e1211455fbc00e8"
  token: "XeNLbIvvlTu_YtMnA3le2IASMK6SGxyzwg3D6Ugi"
  zone_id: "82fda96b998b619c821f72ceed55e427"
  invalidation_timeout: "1s"
db:
  user: "postgres"
  password: "1234"
  db: "postgres"
  host: "127.0.0.1"
  port: "5431"
tracing:
  svc_name: "firewall-cloudflare-executor"
# jaeger_endpoint: ""
